---
# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercise3
  namespace: exercise3
  labels:
    app: exercise3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exercise3
  template:
    metadata:
      labels:
        app: exercise3
    spec:
      containers:
      - name: exercise3
        image: bddagostino/exercise1:latest
        ports:
        - containerPort: 8080
        env:
          - name: MYSQL_HOST
            value: "exercise3-mariadb-service"
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: mariadb-secrets
                key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mariadb-secrets
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-secrets
                key: MYSQL_PASSWORD
---
# do we want to expose it?
apiVersion: v1
kind: Service
metadata:
  name: exercise3-service
  namespace: exercise3
spec:
  type: NodePort
  selector:
    app: exercise3
  ports:
    - port: 80           
      targetPort: 8080  