services:
  db:
    image: mariadb:latest
    container_name: db
    networks:
      - devops-network
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: R00tP4ssw0rd
      MYSQL_DATABASE: devopsdb
      MYSQL_USER: devopsuser
      MYSQL_PASSWORD: D3v0ps.2025!
    volumes:
      - /etc/localtime:/etc/localtime:ro
  web:
    image: bddagostino/exercise1:latest
    container_name: web
    networks:
      - devops-network
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: devopsdb
      MYSQL_USER: devopsuser
      MYSQL_PASSWORD: D3v0ps.2025!
  
    
networks:
  devops-network: