- hosts: all
  become: yes
  tasks:
    - fail:
       msg: "OS should be Ubuntu 24.04, not {{ ansible_distribution }} {{ ansible_distribution_version }}"
      when: ansible_distribution != 'Ubuntu' or ansible_distribution_version != '24.04'

    - name: update APT packages
      apt:
        update_cache: yes

    - name: reboot and wait for reboot to complete
      reboot:

    - name: disable SWAP
      shell: |
        swapoff -a

    - name: disable SWAP in fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'

    - name: install APT Transport HTTPS
      apt:
        name: apt-transport-https
        state: present

    - name: add Docker apt-key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker-apt-keyring.asc
        mode: '0644'
        force: true

    - name: add Docker's APT repository
      apt_repository:
        repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }} signed-by=/etc/apt/keyrings/docker-apt-keyring.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes
    
    - name: install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: true

    - name: install Docker Compose
      apt:
        name: docker-compose
        state: present
        update_cache: true
    
    - name: Run whoami without become.
      command: whoami
      changed_when: false
      become: false
      register: whoami

    - name: Set a fact with the user name.
      set_fact:
        login_user: '{{ whoami.stdout }}'

    - name: Add the current user to 'docker' group
      become: yes
      user:
        name: '{{ whoami.stdout }}'
        groups: docker
        append: yes

    - name: Reset SSH connection to refresh user groups
      meta: reset_connection