{{- if .Values.env }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "exercise3.fullname" . }}
  labels:
    {{- include "exercise3.labels" . | nindent 4 }}
data:
{{- range .Values.env }}
  {{ .name }}: {{ .value | quote }}
{{- end }}
{{- end }}