- hosts: all
  tasks:
    - name: run docker compose
      community.docker.docker_compose_v2:
        project_src: "/home/{{ whoami.stdout }}/compose"
        files:
        - docker-compose.yml